### ISSUE TITLE
Messages only if backup failed

### ISSUE THREAD

**Issue by Skyfay** [jameslloyd/duplicati-discord-notification#1]
Thank you for this great tool. Is it possible to set up that only a message is sent when the backup has failed?

Thanks for help :)

**Comment by jameslloyd** [comment]
Notification levels are live on https://duplicati-notifications.lloyd.ws 
either regenerate your notification URL on the page or simply add &level=Warning to the end of the URL you're already using

**Comment by Skyfay** [comment]
Thank you very much for this quick update. This really helps me a lot :)
